/*This file was generated by NativeWind. Do not edit!*/
import nativewind = require('nativewind');

const { NativeWindStyleSheet } = nativewind;

export = NativeWindStyleSheet.create({
  styles: {
    '*': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    '': {
      borderTopWidth: 0,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderLeftWidth: 0,
      borderStyle: 'solid',
      borderTopColor: '#e5e7eb',
      borderRightColor: '#e5e7eb',
      borderBottomColor: '#e5e7eb',
      borderLeftColor: '#e5e7eb',
    },
    html: {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    ':host': {
      lineHeight: 1.5,
      fontFamily: 'ui-sans-serif',
    },
    body: {
      backgroundColor: '#ffffff',
    },
    hr: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    'abbr:where([title])': {
      textDecorationLine: 'underline',
      textDecorationColor: 'black',
      textDecorationStyle: 'dotted',
    },
    code: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    kbd: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    samp: {
      fontFamily: 'ui-monospace',
      fontSize: '1em',
    },
    pre: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    small: {
      fontSize: '80%',
    },
    sub: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    sup: {
      fontSize: '75%',
      lineHeight: 0,
      position: 'relative',
    },
    button: {
      backgroundColor: 'transparent',
    },
    input: {
      opacity: 1,
      color: '#9ca3af',
    },
    optgroup: {
      fontFamily: 'inherit',
      fontSize: '100%',
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    select: {
      textTransform: 'none',
    },
    textarea: {
      opacity: 1,
      color: '#9ca3af',
    },
    "input:where([type='button'])": {
      backgroundColor: 'transparent',
    },
    "input:where([type='reset'])": {
      backgroundColor: 'transparent',
    },
    "input:where([type='submit'])": {
      backgroundColor: 'transparent',
    },
    ':-moz-ui-invalid': {
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowRadius: 0,
      shadowColor: 'black',
      shadowOpacity: 1,
    },
    blockquote: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dl: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    dd: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h1: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h2: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h3: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h4: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h5: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    h6: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    figure: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    p: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
    },
    fieldset: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    legend: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ol: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    ul: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    menu: {
      marginTop: 0,
      marginRight: 0,
      marginBottom: 0,
      marginLeft: 0,
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    dialog: {
      paddingTop: 0,
      paddingRight: 0,
      paddingBottom: 0,
      paddingLeft: 0,
    },
    img: {
      maxWidth: '100%',
    },
    video: {
      maxWidth: '100%',
    },
    '[hidden]': {
      display: 'none',
    },
    'body@0': {
      backgroundColor: '#000000',
    },
    container: {
      width: '100%',
    },
    'container@0': {
      maxWidth: 640,
    },
    'container@1': {
      maxWidth: 768,
    },
    'container@2': {
      maxWidth: 1024,
    },
    'container@3': {
      maxWidth: 1280,
    },
    'container@4': {
      maxWidth: 1536,
    },
    spinner: {
      position: 'relative',
      width: 70,
      height: 70,
      transform: [
        {
          translateY: -5,
        },
        {
          translateX: 76,
        },
        {
          scale: 0.3,
        },
      ],
    },
    'div:after': {
      position: 'absolute',
      top: 5,
      left: 37,
      width: 6,
      height: 20,
      borderTopLeftRadius: '20%',
      borderTopRightRadius: '20%',
      borderBottomRightRadius: '20%',
      borderBottomLeftRadius: '20%',
      backgroundColor: 'black',
    },
    'div:after@0': {
      backgroundColor: 'white',
    },
    'div:nth-child(1)': {
      transform: [
        {
          rotate: '0deg',
        },
      ],
    },
    'div:nth-child(2)': {
      transform: [
        {
          rotate: '30deg',
        },
      ],
    },
    'div:nth-child(3)': {
      transform: [
        {
          rotate: '60deg',
        },
      ],
    },
    'div:nth-child(4)': {
      transform: [
        {
          rotate: '90deg',
        },
      ],
    },
    'div:nth-child(5)': {
      transform: [
        {
          rotate: '120deg',
        },
      ],
    },
    'div:nth-child(6)': {
      transform: [
        {
          rotate: '150deg',
        },
      ],
    },
    'div:nth-child(7)': {
      transform: [
        {
          rotate: '180deg',
        },
      ],
    },
    'div:nth-child(8)': {
      transform: [
        {
          rotate: '210deg',
        },
      ],
    },
    'div:nth-child(9)': {
      transform: [
        {
          rotate: '240deg',
        },
      ],
    },
    'div:nth-child(10)': {
      transform: [
        {
          rotate: '270deg',
        },
      ],
    },
    'div:nth-child(11)': {
      transform: [
        {
          rotate: '300deg',
        },
      ],
    },
    'div:nth-child(12)': {
      transform: [
        {
          rotate: '330deg',
        },
      ],
    },
    '0%@0': {
      opacity: 1,
    },
    '100%@0': {
      opacity: 0,
    },
    absolute: {
      position: 'absolute',
    },
    relative: {
      position: 'relative',
    },
    flex: {
      display: 'flex',
    },
    hidden: {
      display: 'none',
    },
    'bg-red-500': {
      backgroundColor: 'rgba(239, 68, 68, 1)',
    },
    underline: {
      textDecorationLine: 'underline',
    },
  },
  atRules: {
    body: [[['media', '(prefers-color-scheme: dark)']]],
    container: [
      [['media', '(min-width: 640px)']],
      [['media', '(min-width: 768px)']],
      [['media', '(min-width: 1024px)']],
      [['media', '(min-width: 1280px)']],
      [['media', '(min-width: 1536px)']],
    ],
    'div:after': [[['media', '(prefers-color-scheme: dark)']]],
    '0%': [[['keyframes', 'spinner']]],
    '100%': [[['keyframes', 'spinner']]],
  },
  transforms: {
    spinner: true,
    'div:nth-child(1)': true,
    'div:nth-child(2)': true,
    'div:nth-child(3)': true,
    'div:nth-child(4)': true,
    'div:nth-child(5)': true,
    'div:nth-child(6)': true,
    'div:nth-child(7)': true,
    'div:nth-child(8)': true,
    'div:nth-child(9)': true,
    'div:nth-child(10)': true,
    'div:nth-child(11)': true,
    'div:nth-child(12)': true,
  },
  topics: {
    container: ['width'],
  },
});
